spring:
  application:
    name: files-notifications-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/document_search_engine
  cloud:
    consul:
        host: consul-server
        port: 8500
        discovery:
            port: 8080
            prefer-ip-address: true
            healthCheckPath: /actuator/health
    stream:
        kafka:
            binder:
                brokers: kafka:9092
                requiredAcks: 1
                auto-create-topics: false
                configuration:
                    auto:
                        offset.reset: latest
            bindings:
                processed-files-state:
                    consumer:
                        autoCommitOffset: false
        bindings:
            processed-files-state:
                group: notifications-collector
  data:
    mongodb:
        authentication-database: admin
        database: files
        host: mongo
        port: 27017
        username: devroot
        password: devroot

## Spring Open API
springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs

## Stomp Configuration
stomp:
    destination.broadcast: /topic/unresolved.user.dest
    registry.broadcast: /topic/registry.broadcast
    host: rabbitmq-stomp
    port: 61613
    client:
        username: guest
        passcode: guest

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  com.dreamsoftware.documentsearchengine: DEBUG
  org.springframework.web.reactive.function.client: TRACE

server.port: 8080