spring:
  application:
    name: files-search-service
  cloud:
    consul:
        host: localhost
        port: 8500
        discovery:
            port: 8080
            prefer-ip-address: true
            healthCheckPath: /actuator/health

## Spring Open API
springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE
  com.dreamsoftware.documentsearchengine: DEBUG

server.port: 8080