spring:
  application:
    name: files-management-service
  cloud:
    consul:
        host: consul-server
        port: 8500
        discovery:
            port: 8080
            prefer-ip-address: true
            healthCheckPath: /actuator/health

## SFTP Config
sftp:
    hostname: sftp
    port: 22
    username: ssanchez
    password: ssanchez00
    remoteFolder: uploads/

## Uploads Config
uploads:
    directory: /opt/uploads

## Spring Open API
springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  com.dreamsoftware.documentsearchengine: DEBUG
  org.springframework.web.reactive.function.client: TRACE

server.port: 8080