spring:
  application:
    name: files-metadata-service
  cloud:
    consul:
        host: 127.0.0.1
        port: 8500
        discovery:
            port: 8080
            prefer-ip-address: true
            healthCheckPath: /actuator/health
  data:
    mongodb:
        authentication-database: admin
        database: files
        host: 127.0.0.1
        port: 27017
        username: devroot
        password: devroot

## Spring Open API
springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE

server.port: 8081