spring:
  application:
    name: files-metadata-service
  cloud:
    consul:
        host: consul
        port: 8500
        discovery:
            port: 8080
            prefer-ip-address: true
            healthCheckPath: /actuator/health
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/document_search_engine

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE

server.port: 8080