spring:
  application:
    name: gateway-service
  cloud:
    consul:
        host: consul
        port: 8500
    discovery:
        register: false
        registerHealthCheck: false
    gateway:
        discovery:
            locator:
                enabled: true
        default-filters:
            - TokenRelay
        routes:
            - id: files-metadata-service
              uri: lb://files-metadata-service
              predicates:
                - Path=/metadata/**
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/metadata/(?<path>.*), /$\{path}
            - id: files-search-service
              uri: lb://files-search-service
              predicates:
                - Path=/search/**
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/search/(?<path>.*), /$\{path}
            - id: files-management-service
              uri: lb://files-management-service
              predicates:
                - Path=/management/**
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/management/(?<path>.*), /$\{path}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8090/auth/realms/document_search_engine/protocol/openid-connect/token
            authorization-uri: http://localhost:8090/auth/realms/document_search_engine/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8090/auth/realms/document_search_engine/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-with-test-scope:
            provider: keycloak
            client-id: keycloak-with-test-scope
            client-secret: 9a7998ba-2ad3-4f6f-8582-410e5221a3f0
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

server.port: 8080

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE